# 2018036068 유창성

In [1]:
import numpy as np

#### q : number of symbols
#### n : length of codeword
#### k : length of information
#### M : $ q^k $ / size of block code

In [2]:
codeword_1 = np.array([0,1,0,1,0,0,0])
information_1 = np.array([1,1,0])
print('q :', np.unique(codeword_1),'\t\t(←중복을 제거하여 symbol의 종류를 알아낼 수 있다)', end='\n'*2)

print('n :', len(codeword_1), '\t\t(←codeword의 길이를 알아낼 수 있다.)', end='\n'*2)

print('k :', len(information_1), '\t\t(←information의 길이를 알아낼 수 있다.)', end='\n'*2)

print('M :', len(np.unique(codeword_1))**len(information_1),
                                          '\t\t (←블록코드의 사이즈를 알아낼 수 있다)', end='\n'*2)

q : [0 1] 		(←중복을 제거하여 symbol의 종류를 알아낼 수 있다)

n : 7 		(←codeword의 길이를 알아낼 수 있다.)

k : 3 		(←information의 길이를 알아낼 수 있다.)

M : 8 		 (←블록코드의 사이즈를 알아낼 수 있다)



### $ c=i·G $
#### c : codeword (1, n)
#### i : information (1, k)
#### G : generator matrix (k, n)

### $ G = [I|P] $
#### I : identity matrix (k×k)
#### P : coefficient matrix (k×(n-k))

In [89]:
identity_matrix_1 = np.identity(4)

coeffiecient_matrix_1 = np.array([[1, 1, 1],
                                [1, 0, 1],
                                [1, 1, 0],
                                [0, 1, 1]])
generator_matrix_1 = np.concatenate((identity_matrix_1, coeffiecient_matrix_1), axis=1)

print('I :',identity_matrix_1, 'P :', coeffiecient_matrix_1, ' G :', generator_matrix_1, sep='\n')

I :
[[1. 0. 0. 0.]
 [0. 1. 0. 0.]
 [0. 0. 1. 0.]
 [0. 0. 0. 1.]]
P :
[[1 1 1]
 [1 0 1]
 [1 1 0]
 [0 1 1]]
 G :
[[1. 0. 0. 0. 1. 1. 1.]
 [0. 1. 0. 0. 1. 0. 1.]
 [0. 0. 1. 0. 1. 1. 0.]
 [0. 0. 0. 1. 0. 1. 1.]]


### $ c·H^T = 0 $
### $ c=i·G $
### $ H = [P^T|I] $
### $ H^T = [\frac{P}{I_{n-k}}] $
### $ c·H^T = i·G·H^T = 0$
### $ ∴ i·G·H^T = i[I|P][\frac{P}{I_{n-k}}] = I·P + P·I = 0 $
#### c : codeword
#### H : parity check matrix


In [22]:
#codeword_2 = np.array([])

parity_check_matrix_1 = np.array([[1,1,1,0,1,0,0],
                                  [1,0,1,1,0,1,0],
                                  [1,1,0,1,0,0,1]])

identity_matrix_2 = parity_check_matrix_1[: , 4: ]
print('단위행렬 I :\n', identity_matrix_2, end='\n\n')

coeffiecient_matrix_2_transpose = parity_check_matrix_1[: , :4]
print('P 전치행렬 :\n', coeffiecient_matrix_2, end='\n\n')
coeffiecient_matrix_2 = parity_check_matrix_1[0:3 , 0:4].T
                                    # ↑  .T는 넘파이 라이브러리에서 제공하는 전치행렬 메소드다.
print('P : :\n', coeffiecient_matrix_2)

단위행렬 I :
 [[1 0 0]
 [0 1 0]
 [0 0 1]]

P 전치행렬 :
 [[1 1 1]
 [1 0 1]
 [1 1 0]
 [0 1 1]]

P : :
 [[1 1 1]
 [1 0 1]
 [1 1 0]
 [0 1 1]]


#### ↓Solving Hamming weight $ d_W $

In [72]:
code_ex1 = np.array([0,0,0,1,0])
print('codeword\'s hamming weight :', np.count_nonzero(code_ex1), end='\n'*3)


code_ex2 = np.array([[0,0,0,0,0],
                     [0,0,0,0,1],
                     [0,1,1,1,0]])
for i in range(3):
    print('codeword[{}]\'s hamming weight :'.format(i), np.count_nonzero(code_ex2[i]))

codeword's hamming weight : 1


codeword[0]'s hamming weight : 0
codeword[1]'s hamming weight : 1
codeword[2]'s hamming weight : 3


#### ↓ Solving Hamming distance $ d_H $

In [28]:
code_ex3 = np.array([[1,0,1,1],
              [0,0,0,0]])
code_ex4 = np.array([[0,1,1,1],
              [1,1,1,1]])
for i in range(2):
    print('hamming distance between a[{}] and b[{}] :'.format(i, i),
                              np.count_nonzero(code_ex3[i] != code_ex4[i]))

hamming distance between a[0] and b[0] : 2
hamming distance between a[1] and b[1] : 4


# ☆☆☆☆☆여기까지가 개념정리☆☆☆☆☆
# ↓ 본격적인 syndrome decoding

#### Write a python code for decoding (7, 4) Block code
#### $ n = 7 $ and $ k = 4$

##### ↓넘파이 라이브러리 선언

In [31]:
import numpy as np

#### $G$ = generator matrix
### $ G = [I|P] $
#### size of $ G = (4, 7) $
##### ↓Define the generator matrix

In [76]:
generator_matrix = np.array([[1,0,0,0,1,1,1],
                             [0,1,0,0,1,0,1],
                             [0,0,1,0,1,1,0],
                             [0,0,0,1,0,1,1]])
print('generator matrix :', generator_matrix, sep='\n'*2)

generator matrix :

[[1 0 0 0 1 1 1]
 [0 1 0 0 1 0 1]
 [0 0 1 0 1 1 0]
 [0 0 0 1 0 1 1]]


#### $ I $ = identity matrix
#### size of $ I = (k,k) = (4,4) $
##### ↓ $G$ 에서 $I$ 추출하기

In [77]:
identity_matrix = generator_matrix[ : , :4]
print('identity matrix :', identity_matrix, sep='\n'*2)

identity matrix :

[[1 0 0 0]
 [0 1 0 0]
 [0 0 1 0]
 [0 0 0 1]]


#### $P$ = coefficient matrix
### size of $ P = (k,(n-k)) = (4,3) $ 
##### ↓ $G$ 에서 $P$ 추출하기

In [78]:
coeffiecient_matrix = generator_matrix[ : , 4:]
print('coefficient matrix :', coeffiecient_matrix, sep='\n'*2)

coefficient matrix :

[[1 1 1]
 [1 0 1]
 [1 1 0]
 [0 1 1]]


#### $H$ = parity check matrix
### $H = [P^T|I_{n-k}]$
##### ↓ Define the parity-check matrix

##### At first, define the $ P^T $
### size of $ P^T = ((n-k),k) = (3,4) $
##### ↓ Define the $ P^T $

In [79]:
coeffiecient_matrix_transposed = coeffiecient_matrix.T
print('transpose of coefficient matrix :', coeffiecient_matrix_transposed, sep='\n'*2)


transpose of coefficient matrix :

[[1 1 1 0]
 [1 0 1 1]
 [1 1 0 1]]


##### Then, define the $ I_{n-k} $
#### size of $ I_{n-k} = ((n-k),(n-k)) = (3,3) $
##### ↓ define the $ I_{n-k} $

In [80]:
identity_matrix_scaled_____n_minus_k = identity_matrix[:3 , :3]
print('scaled identity matrix :', identity_matrix_scaled_____n_minus_k, sep='\n'*2)

scaled identity matrix :

[[1 0 0]
 [0 1 0]
 [0 0 1]]


##### Finally, we can find the $ H $

In [81]:
parity_check_matrix = np.concatenate((coeffiecient_matrix_transposed, identity_matrix_scaled_____n_minus_k),
                                                                                            axis=1)
print('parity check matrix :', parity_check_matrix, sep='\n'*2)

parity check matrix :

[[1 1 1 0 1 0 0]
 [1 0 1 1 0 1 0]
 [1 1 0 1 0 0 1]]


#### $H^T$ = transpose of parity check matrix
### $ H^T = [\frac{P}{I_{n-k}}] $
##### ↓define the $ H^T $

In [82]:
parity_check_matrix_transposed = np.concatenate((coeffiecient_matrix, identity_matrix_scaled_____n_minus_k),
                                                                                            axis=0)
# parity_check_matrix_transposed = parity_check_matrix.T   // 동일한 방법
print(parity_check_matrix_transposed)

[[1 1 1]
 [1 0 1]
 [1 1 0]
 [0 1 1]
 [1 0 0]
 [0 1 0]
 [0 0 1]]


#### ↓Define the received codeword

In [95]:
received_codeword = np.array([1,0,0,0,1,0,1])
print(received_codeword)

[1 0 0 0 1 0 1]


#### s = syndrome of received codeword
### $ s = rH^T $
##### ↓ Calculate the syndrome

In [96]:
syndrome = np.dot(parity_check_matrix, received_codeword) % 2
print('syndrome of received code :', syndrome)

syndrome of received code : [0 1 0]


##### ↑ syndrome이 [0 0 0]을 뜻하면 error가 발견되지 않은 올바른 코드워드를 수신했다는 것이고
##### [0 1 0]이면 parity check matrix H의 6열과 같은 것으로 보아 
##### 6번째 비트가 잘못 수신되었다는 것을 짐작할 수 있다.

##### ↓Initialize the error vector to all zeros

In [85]:
e = np.array([0,0,0,0,0,0,0])

##### Check if the syndrome is non-zero

In [88]:
if not np.array_equal(syndrome, [0,0,0]):
    # Find the position of the error
    error_pos = np.sum(syndrome * [1,2,4]) - 1   # ←2^0, 2^1, 2^2을 의미하며
    print(error_pos)
    
    # Set the corresponding element in the error vector to 1
    e[error_pos] = 1   # e=[0,0,0,0,0,0,0]의 틀린 비트에 1을 대체한다.
    
    # Correct the received codeword
    r_corrected = (received_codeword - e) % 2   # 오류난 코드워드에 수정된 e(틀린 비트에 1을 대체한 것)에
    print(r_corrected)                          # 뺄셈을 하여 XOR 연산을 한다.
else:
    # If the syndrome is zero, no error occurred
    r_corrected = received_codeword   #오류가 발견되지 않았다면
    print(r_corrected)

[1 0 0 0 1 1 1]


In [68]:
# Extract the original message from the corrected codeword
m = np.dot(r_corrected[:4], np.identity(4)) % 2

# Print the original message and the corrected codeword
print("Received sequence:", received_codeword)
print("Original message:", m)
print("Corrected codeword:", r_corrected)


Received sequence: [1 0 0 0 1 1 1]
Original message: [1. 0. 0. 1.]
Corrected codeword: [1 0 0 1 1 1 1]


# △△△△△여기까지가 과제△△△△△

### 3 repetition code

In [ ]:
def encode(message):
    # Repeat each bit 3 times
    encoded = ''.join(bit * 3 for bit in message)
    return encoded

def decode(encoded):
    # Remove duplicates and return the most common bit
    decoded = ''.join(max(set(encoded[i:i+3]), key=encoded[i:i+3].count) for i in range(0, len(encoded), 3))
    return decoded

In [ ]:
message = '101010'
encoded = encode(message)
print(encoded)  # output: '111000111000'

In [ ]:
decoded = decode(encoded)
print(decoded)  # output: '101010'

### write a python code to build (7 4) block code standard array (??)

In [ ]:
import numpy as np

# Define the generator matrix
G = np.array([[1, 0, 0, 0, 1, 1, 1],
              [0, 1, 0, 0, 1, 0, 1],
              [0, 0, 1, 0, 0, 1, 1],
              [0, 0, 0, 1, 1, 1, 0]])

# Define the parity-check matrix
H = np.array([[1, 1, 0, 1, 1, 0, 0],
              [1, 0, 1, 1, 0, 1, 0],
              [0, 1, 1, 1, 0, 0, 1]])

In [ ]:
# Define the identity matrix
I = np.eye(4)

In [ ]:
H.T

In [ ]:
[np.zeros((3, 3)), H.T]

In [ ]:
np.block([np.zeros((3, 3)), H])

In [ ]:
S = [  0   H^T ]
    [  H    0  ]


In [ ]:
import numpy as np

A = np.array([[1, 2], [3, 4]])
B = np.array([[5, 6], [7, 8]])

C = np.block([[A, B]])

print(C)